# Generated by Django 4.2.5 on 2023-11-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0003_profile_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="transactions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=200, null=True)),
                ("receiver", models.CharField(max_length=200, null=True)),
                ("amount", models.IntegerField(null=True)),
                ("time_transtaction", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
